# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.ImageField(upload_to=None)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
