# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numbers',
            new_name='Number',
        ),
    ]
