# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200523_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='photo_path',
            new_name='photo',
        ),
    ]
