# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200523_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
